CmsShoppingCart/Controllers/CartController.cs
using CmsShoppingCart.Models.Data;
using CmsShoppingCart.Models.ViewModels.Cart;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace CmsShoppingCart.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        public ActionResult Index()
        {
            var cart = Session["cart"] as List<CartVM> ?? new List<CartVM>();

            if (cart.Count == 0 || Session["cart"] == null)
            {
                ViewBag.Message = "Your cart is empty.";
                return View();
            }

            decimal total = 0m;

            foreach (var item in cart)
            {
                total += item.Total;
            }

            ViewBag.GrandTotal = total;

            return View(cart);
        }

        public ActionResult CartPartial()
        {
            CartVM model = new CartVM();
            int qty = 0;
            decimal price = 0m;

            if (Session["cart"] != null)
            {
                var list = (List<CartVM>)Session["cart"];
                foreach (var item in list)
                {
                    qty += item.Quantity;
                    price += item.Total;
                }

                model.Quantity = qty;
                model.Price = price;
            }
            else
            {
                model.Quantity = 0;
                model.Price = 0m;
            }

            return PartialView(model);
        }

        public ActionResult AddToCartPartial(int id)
        {
            List<CartVM> cart = Session["cart"] as List<CartVM> ?? new List<CartVM>();

            CartVM model = new CartVM();

            using (Db db = new Db())
            {
                ProductDTO product = db.Products.Find(id);
                var productInCart = cart.FirstOrDefault(m => m.ProductId == id);
                if (productInCart == null)
                {
                    cart.Add(new CartVM
                    {
                        ProductId = product.Id,
                        ProductName = product.Name,
                        Quantity = 1,
                        Price = product.Price,
                        Image = product.ImageName
                    });
                }
                else
                {
                    productInCart.Quantity++;
                }
            }

            int qty = 0;
            decimal price = 0m;

            foreach (var item in cart)
            {
                qty += item.Quantity;
                price += item.Total;
            }

            model.Quantity = qty;
            model.Price = price;

            Session["cart"] = cart;

            return PartialView(model);
        }

        public JsonResult IncrementProduct(int productId)
        {
            List<CartVM> cart = Session["cart"] as List<CartVM>;

            using (Db db = new Db())
            {
                CartVM model = cart.FirstOrDefault(m => m.ProductId == productId);
                model.Quantity++;
                var result = new { qty = model.Quantity, price = model.Price };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult DecrementProduct(int productId)
        {
            List<CartVM> cart = Session["cart"] as List<CartVM>;

            using (Db db = new Db())
            {
                CartVM model = cart.FirstOrDefault(m => m.ProductId == productId);

                if (model.Quantity > 1)
                {
                    model.Quantity--;
                }
                else
                {
                    model.Quantity = 0;
                    cart.Remove(model);
                }

                var result = new { qty = model.Quantity, price = model.Price };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
        }

        public void RemoveProduct(int productId)
        {
            List<CartVM> cart = Session["cart"] as List<CartVM>;

            using (Db db = new Db())
            {
                CartVM model = cart.FirstOrDefault(m => m.ProductId == productId);

                cart.Remove(model);

            }
        }

        public ActionResult PaypalPartial()
        {
            List<CartVM> cart = Session["cart"] as List<CartVM>;

            return PartialView(cart);

        }

        [HttpPost]
        public void PlaceOrder()
        {
            List<CartVM> cart = (List<CartVM>)Session["cart"];
            string username = User.Identity.Name;
            int orderId = 0;

            using (Db db = new Db())
            {
                OrderDTO orderDTO = new OrderDTO();
                int userId = db.Users.FirstOrDefault(m => m.Username == username).Id;
                orderDTO.UserId = userId;
                orderDTO.CreatedAt = DateTime.Now;

                db.Orders.Add(orderDTO);
                db.SaveChanges();

                orderId = orderDTO.OrderId;

                OrderDetailsDTO orderDetailsDTO = new OrderDetailsDTO();

                foreach (var item in cart)
                {
                    orderDetailsDTO.OrderId = orderId;
                    orderDetailsDTO.UserId = userId;
                    orderDetailsDTO.ProductId = item.ProductId;
                    orderDetailsDTO.Quantity = item.Quantity;

                    db.OrderDetails.Add(orderDetailsDTO);

                    db.SaveChanges();
                }
            }

            var client = new SmtpClient("smtp.mailtrap.io", 2525)
            {
                Credentials = new NetworkCredential("faa87e59a756a7", "ff798d4ef15d56"),
                EnableSsl = true
            };
            client.Send("admin@example.com", "admin@example.com", "New Order", "You have a new order. Order number " + orderId);

            Session["cart"] = null;
        }
    }
}

CmsShoppingCart/Controllers/ShopController.cs
using CmsShoppingCart.Models.Data;
using CmsShoppingCart.Models.ViewModels.Shop;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CmsShoppingCart.Controllers
{
    public class ShopController : Controller
    {
        // GET: Shop
        public ActionResult Index()
        {
            return RedirectToAction("Index", "Pages");
        }

        public ActionResult CategoryMenuPartial()
        {
            List<CategoryVM> categoryVMList;
            using (Db db = new Db())
            {
                categoryVMList = db.Categories.ToArray()
                                                .OrderBy(m => m.Sorting)
                                                .Select(m => new CategoryVM(m))
                                                .ToList();
            }

            return PartialView(categoryVMList);
        }

        public ActionResult Category(string name)
        {
            List<ProductVM> productVMList;

            using (Db db = new Db())
            {
                CategoryDTO categoryDTO = db.Categories.Where(m => m.Slug == name).FirstOrDefault();
                int catId = categoryDTO.Id;

                productVMList = db.Products
                                    .ToArray()
                                    .Where(m => m.CategoryId == catId)
                                    .Select(m => new ProductVM(m))
                                    .ToList();

                //var productCat = db.Products.Where(m => m.CategoryId == catId).FirstOrDefault();
                //ViewBag.CategoryName = productCat.CategoryName;

                var productCat = db.Categories.Find(catId);
                ViewBag.CategoryName = productCat.Name;
            }

            return View(productVMList);
        }

        [ActionName("product-details")]
        public ActionResult ProductDetails(string name)
        {
            ProductVM model;
            ProductDTO dto;

            int id = 0;

            using (Db db = new Db())
            {
                if (!db.Products.Any(m => m.Slug == name))
                {
                    return RedirectToAction("Index");
                }

                dto = db.Products.Where(m => m.Slug == name).FirstOrDefault();
                id = dto.Id;

                model = new ProductVM(dto);
            }

            model.GalleryImages = Directory.EnumerateFiles(Server.MapPath("~/Images/Uploads/Products/" + id + "/Gallery/Thumbs"))
                                                .Select(m => Path.GetFileName(m));

            return View("ProductDetails", model);
        }

    }
}

CmsShoppingCart/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - CmsShoppingCart</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-topcancel">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">CmsShoppingCart</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @Html.Action("PagesMenuPartial", "Pages")
                    @if (Request.IsAuthenticated)
                    {
                        <li><a href="/account/logout">Logout</a></li>
                    }
                    else
                    {
                        if (ViewBag.Title == "Login")
                        {
                            <li class="active"><a href="/account/login">Login</a></li>
                        }
                        else
                        {
                            <li><a href="/account/login">Login</a></li>
                        }
                    }
                    @if (Request.IsAuthenticated && User.IsInRole("User"))
                    {
                        if (ViewBag.Title == "User Profile" || ViewBag.Title == "Orders")
                        {
                            <li class="active">@Html.Action("UserNavPartial", "Account", new { area = "" })</li>
                        }
                        else
                        {
                            <li>@Html.Action("UserNavPartial", "Account", new { area = "" })</li>
                        }
                    }
                </ul>

                @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                {
                    <ul class="navbar-collapse collapse navbar-right adminarea">
                        <li>@Html.ActionLink("Admin Area", "Index", "Dashboard", new { area = "Admin" }, null)</li>
                    </ul>
                }
                else
                {
                    if (ViewBag.Title != "Cart Details")
                    {
                        <ul class="navbar-collapse collapse navbar-right">
                            @Html.Action("CartPartial", "Cart")
                        </ul>
                    }
                }
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="row">
            <div class="ajaxbg">
                <span>
                    <img src="~/Content/img/ajax-loader.gif" />
                </span>
            </div>

            @if (ViewBag.Title != "Create Account" &&
                ViewBag.Title != "Login" &&
                ViewBag.Title != "User Profile" &&
                ViewBag.Title != "Orders")
            {
                <div class="col-xs-12 col-md-2">
                    @Html.Action("CategoryMenuPartial", "Shop")
                </div>
            }

            @if (ViewBag.Title == "User Profile")
            {
                <div class="col-xs-12 col-md-2">
                    <ul>
                        <li><a href="/account/orders">My Orders</a></li>
                    </ul>
                </div>
            }

            @if (ViewBag.Title == "Orders")
            {
                <div class="col-xs-12 col-md-2">
                    <ul>
                        <li><a href="/account/user-profile">My Profile</a></li>
                    </ul>
                </div>
            }

            @if (ViewBag.Sidebar == "Yes")
            {
                <div class="col-xs-12 col-md-7">
                    @RenderBody()
                </div>
                <div class="col-xs-12 col-md-3">
                    @Html.Action("SidebarPartial", "Pages")
                </div>
            }
            else
            {
                <div class="col-xs-12 col-md-10">
                    @RenderBody()
                </div>

            }

        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/scripts")
    @RenderSection("scripts", required: false)
</body>
</html>